<a href="https://colab.research.google.com/github/lichkim/VQE_Summer_Internship/blob/master/tutorial_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# install required packages
!pip install -U nlopt
import numpy as np
import tensorflow as tf
import nlopt
from itertools import product
import logging

2023-08-01 07:52:18.474441: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-01 07:52:18.517883: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-01 07:52:18.518887: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-01 07:52:19.480545: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [2]:
class Sigma:

    '''
    Sigma class generates algebraic primitives required to compute the system of implicit ODEs for Euler angles.
    '''

    def __init__(self, *args):
            self.string = [i for i in args] #유저가 입력하는 args를 리스트로 바꿉니다 예시에는 args로 1, 2가 들어갔습니다. 첫 번째 args는 사용할 pauli matrix를 결정합니다.(1:I, 2:X, 3:Y, 4:Z)
            self.order = len(args)          #그 string의 길이를 order로 합니다 지금은 1, 2이므로 2입니다.
            self.digit = sum([args[i]*4**(self.order-i-1) for i in range(len(args))])   #(4 * args[i])^(args길이-1-i)를 i=0~args길이만큼 반복한 것을 더합니다. 예시의 경우 4+1=5 입니다.
            
            #single qubit에 가하는 pauli gate의 matrix form입니다.
            self.pauli = tf.constant(   #4개의 pauli matrix입니다. 순서대로 I, X, Y, Z입니다.
                [  
                    [
                        [-1j/2,0],
                        [0,-1j/2]
                    ],
                    [
                        [0, 1j/2],
                        [1j/2, 0]
                    ],
                    [
                        [0, -1/2],
                        [1/2, 0]
                    ],
                    [
                        [1j/2, 0],
                        [0, -1j/2]
                    ]
                ],dtype=tf.complex64,shape=(4,2,2))
            
            
            self.__struct_const_0 = tf.constant(   
                [
                    np.zeros([4,4]),
                    [[0.0, 0.0, 0.0, 0.0],[0.0, 0.0, 0.0, 0.0],[0.0, 0.0, 0.0, -1.0],[0.0, 0.0, 1.0, 0.0]],
                    [[0.0, 0.0, 0.0, 0.0],[0.0, 0.0, 0.0, 1.0],[0.0, 0.0, 0.0, 0.0],[0.0, -1.0, 0.0, 0.0]],
                    [[0.0, 0.0, 0.0, 0.0],[0.0, 0.0, -1.0, 0.0],[0.0, 1.0, 0.0, 0.0],[0.0, 0.0, 0.0, 0.0]]
                    ], dtype=tf.complex64
            )
            self.__struct_const_1 = tf.constant(
                [
                    -1j*np.eye(4),
                    -1j*np.array([[0.0, 1.0, 0.0, 0.0],[1.0, 0.0, 0.0, 0.0],[0.0, 0.0, 0.0, 0.0],[0.0, 0.0, 0.0, 0.0]]),
                    -1j*np.array([[0.0, 0.0, 1.0, 0.0],[0.0, 0.0, 0.0, 0.0],[1.0, 0.0, 0.0, 0.0],[0.0, 0.0, 0.0, 0.0]]),
                    -1j*np.array([[0.0, 0.0, 0.0, 1.0],[0.0, 0.0, 0.0, 0.0],[0.0, 0.0, 0.0, 0.0],[1.0, 0.0, 0.0, 0.0]])
                    ], dtype=tf.complex64
            )
            self.__vector = tf.constant([
                [1,0,0,0],
                [0,1,0,0],
                [0,0,1,0],
                [0,0,0,1]], dtype=tf.float32
            )
            
            self.index_perm = list(range(0,self.order*2,2)) + list(range(1,self.order*2+1,2))   #index permuation. 0부터의 짝수 이후 1부터의 홀수를 셉니다
            self.fundamental = self.rep_fundamental()   #추후 rep_fundamental 메서드에 설명합니다. 파이썬 문법적으로는 rep_fundamental메서드가 객체가 되어 이를 부른것입니다.
            self.adjoint = self.rep_adjoint()           #추후 rep_adjoint 메서드에 설명합니다.
            
            #self.fundamental_z를 구하기 위해 필요한 부가적인 연산들입니다.
            self.fundamental_z = tf.eye(2,dtype=tf.complex64)
            for i in range(1,self.order):
                self.fundamental_z = tf.tensordot(self.fundamental_z,tf.eye(2,dtype=tf.complex64),axes=0)
            self.fundamental_z = tf.transpose(self.fundamental_z,perm=self.index_perm)
            
            #self.adjoint_z를 구하기 위해 필요한 부가적인 연산들입니다.
            self.adjoint_z = tf.eye(4,dtype=tf.float32)
            for i in range(1,self.order):
                self.adjoint_z = tf.tensordot(self.adjoint_z,tf.eye(4,dtype=tf.float32),axes=0)
            self.adjoint_z = tf.transpose(self.adjoint_z,perm=self.index_perm)
            self.adjoint_square = tf.tensordot(self.adjoint,self.adjoint,axes=self.order)
            self.adj_vec = self.adj_vector()            #추후 adj_vector 메서드에 설명합니다.

    def rep_fundamental(self):
        index = self.string
        ret = self.pauli[index[0]]  # args의 첫 번째 숫자에 따라 다른 pauli matrix를 부릅니다.
        for i in range(1,len(index)):
            ret = 2j*tf.tensordot(ret,self.pauli[index[i]],axes=0)
        return tf.transpose(ret,perm=self.index_perm)

    def rep_adjoint(self):
        return tf.transpose(tf.cast(self.__rep_adjoint(self.string),dtype=tf.float32),perm=self.index_perm)

    def __rep_adjoint(self,sigma,center=False,grade=False):
        order = len(sigma)  #sigma는 order의 값을 구하는대만 사용됩니다. 이럴거면 코드 자체를 sigma를 받는게 아니라 order를 받는걸로 짜면 안되나
        if grade:
            ret = self.__struct_const_1[sigma[0]]
        else:
            ret = self.__struct_const_0[sigma[0]]

        """
        Base case: order == 1 
            -grade == False  // ret=__struct_const_0(sigma[0])
            -grade == True   // ret=__struct_const_1(sigma[0])
            
        이후의 케이스(order > 1)에 대해서는 함수를 재귀적으로 호출합니다.
        """
        if order > 1:
            if grade:
                ret = 1.j* (
                    tf.tensordot(self.__rep_adjoint(sigma[0:order-1],center=True,grade=True),  self.__rep_adjoint([sigma[order-1]],center=True,grade=True),axes=0) +
                    tf.tensordot(self.__rep_adjoint(sigma[0:order-1],center=True,grade=False), self.__rep_adjoint([sigma[order-1]],center=True,grade=False),axes=0)
                    )
            else:
                ret = 1.j* (
                    tf.tensordot(self.__rep_adjoint(sigma[0:order-1],center=True,grade=True),  self.__rep_adjoint([sigma[order-1]],center=True,grade=False),axes=0) +
                    tf.tensordot(self.__rep_adjoint(sigma[0:order-1],center=True,grade=False), self.__rep_adjoint([sigma[order-1]],center=True,grade=True),axes=0)
                    )


        return ret

    def adj_vector(self):
        index = self.string
        ret = self.__vector[index[0]]
        for i in range(1,len(index)):
            ret = tf.tensordot(ret,self.__vector[index[i]],axes=0)
        return ret
    
    @tf.function
    def exp_fundamental(self,x):
        s = tf.cast(tf.math.sin(x/2),tf.complex64)
        c = tf.cast(tf.math.cos(x/2),tf.complex64)
        return tf.tensordot(c, self.fundamental_z,axes=0) + tf.tensordot(2*s,  self.fundamental,axes=0)
    
    @tf.function
    def exp_adjoint(self,x):
        return self.adjoint_z + tf.tensordot(tf.math.sin(x), self.adjoint,axes=0) + tf.tensordot((1 - tf.math.cos(x)), self.adjoint_square,axes=0)

In [3]:
s1 = Sigma(1,2)
s1.fundamental

2023-08-01 07:52:20.970575: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-08-01 07:52:20.971279: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1960] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


<tf.Tensor: shape=(2, 2, 2, 2), dtype=complex64, numpy=
array([[[[ 0. +0.j,  0. +0.j],
         [ 0. +0.j,  0.5+0.j]],

        [[ 0. +0.j,  0. +0.j],
         [-0.5+0.j,  0. +0.j]]],


       [[[ 0. +0.j,  0.5+0.j],
         [ 0. +0.j,  0. +0.j]],

        [[-0.5+0.j,  0. +0.j],
         [ 0. +0.j,  0. +0.j]]]], dtype=complex64)>

In [4]:
class Euler():
    '''
    Euler class genetates various list of indices of sigma strings of the rank n.
    '''
    def __init__(self, order):
        self.order = order
        self.basis = np.array(list(product([0,1,2,3], repeat = order)))
        self.toral = np.array(list(product([0,3], repeat = order)))
        self.kprime = self.__kprime(order)
        self.aprime = self.__aprime(order)
        self.k = self.__k(order)
        self.a = self.__a(order)
        self.kak = np.concatenate((self.k,self.a,self.k),axis=0)
        self.generator = self.__generator(order)
        self.dim = len(self.kak)

    def __kak(self,order):
        if order == 1:
            return np.array([[3],[1],[3]])
        else:
            # return self.__a(order-1)
            return np.concatenate((self.__k(order),self.__a(order),self.__k(order)),axis=0)

    def __kprime(self,order):
        if order == 1:
            return np.array([],dtype=np.int32)
        else:
            # print(self.__kak(order-1))
            return np.insert(self.__kak(order-1),0,0,axis=1)

    def __aprime(self,order):
        if order == 1:
            return np.array([],dtype=np.int32)
        else:
            return np.insert(np.array(list(product([0,3], repeat = order-1))),0,3,axis=1)

    def __k(self,order):
        if order == 1:
            return np.array([[3]])
        else:
            # print(self.kprime)
            # return np.concatenate((self.kprime,self.aprime,self.kprime),axis=0)
            return np.concatenate((self.__kprime(order),self.__aprime(order),self.__kprime(order)),axis=0)

    def __a(self,order):
        if order == 1:
            return np.array([[1]])
        else:
            return np.insert(np.array(list(product([0,3], repeat = order-1))),0,1,axis=1)

    def __generator(self,order):
        if order == 1:
            return np.array([[1],[3]])
        else:
            ret = np.insert(self.__generator(order-1),0,0,axis=1)
            return np.concatenate((ret,self.__a(order),self.__aprime(order)),axis=0)

In [5]:
def generate_first_kind(eu):
  '''
  generates a closure relating canonical coordinates of the first kind to an element in SU(2^n) with respect to sigma strings.
  The argument is an instance of the Euler class.
  '''
  eu_fund = tf.constant(np.array([tf.reshape(Sigma(*s).fundamental,[2**eu.order,2**eu.order]) for s in eu.basis]),dtype=tf.complex128)
  dim = len(eu.basis)
  
  @tf.function
  def first_kind(theta):
    '''
    returns an element of SU(2^n) from given canonical coordinates of the first kind whose generators are sigma strings.
    '''
    theta = tf.cast(theta,tf.complex128)
    return tf.linalg.expm(tf.tensordot(theta,eu_fund,axes=1))
  
  return first_kind

def generate_second_kind(eu):
  '''
  generates a closure relating canonical coordinates of the second kind to an element in SU(2^n) with respect to sigma strings.
  The argument is an instance of the Euler class.
  '''
  eu_fund = tf.constant(np.array([tf.reshape(Sigma(*s).fundamental,[2**eu.order,2**eu.order]) for s in eu.basis]),dtype=tf.complex128);
  dim = len(eu.basis)
  identity = tf.eye(2**eu.order,dtype=tf.complex128)
  @tf.function
  def second_kind(theta):
    '''
    returns an element of SU(2^n) from given canonical coordinates of the second kind whose generators are sigma strings.
    '''
    c = tf.cast(tf.cos(theta/2),tf.complex128)
    s = tf.cast(2*tf.sin(theta/2),tf.complex128)
    ret = c[0] * identity + s[0] * eu_fund[0]
    for i in range(1,dim):
      ret = tf.matmul(ret,(c[i] * identity + s[i] * eu_fund[i]))
    return ret
  return second_kind

In [6]:
def diff_sum(mat1,mat2):
  '''
  sums over the absolute square elementwise difference between two complex matrices.
  '''
  diff = mat1 - mat2
  return tf.cast(tf.reduce_sum(diff*tf.math.conj(diff)),tf.float64)

def generate_diff_sum_grad_fk(mat):
  '''
  generates a function closure computing the diff_sum for a first kind matrix and a complex matrix as well as its gradient.
  '''
  order = tf.cast(tf.experimental.numpy.log2(tf.cast(mat.shape[0],tf.float32)),tf.int16)
  eu = Euler(order)
  fk = generate_first_kind(eu)

  def diff_sum_grad_fk(theta):
    '''
    returns the diff_sum of a first kind matrix and a complex matrix with its gradient.
    The first element of the return is the gradient and the last element is the value of diff_sum.
    '''
    with tf.GradientTape() as tape:
      tape.watch(theta)
      o = diff_sum(mat,fk(theta))

    return tape.gradient(o,theta),o

  return diff_sum_grad_fk

def generate_diff_sum_grad_sk(mat):
  '''
  generates a function closure computing the diff_sum for a second kind matrix and a complex matrix as well as its gradient.
  '''
  order = tf.cast(tf.experimental.numpy.log2(tf.cast(mat.shape[0],tf.float32)),tf.int16)
  eu = Euler(order)
  sk = generate_second_kind(eu)
  def diff_sum_grad_sk(theta):
    '''
    returns the diff_sum of a second kind matrix and a complex matrix with its gradient.
    The first element of the return is the gradient and the last element is the value of diff_sum.
    '''
    with tf.GradientTape() as tape:
      tape.watch(theta)
      o = diff_sum(mat,sk(theta))

    return tape.gradient(o,theta),o

  return diff_sum_grad_sk

In [7]:
# Optimization begins.
def generate_obj_fk(mat):
  '''
  generates an objective function for the optimization problem to find the canonical coordinates of the first kind based on the diff_sum.
  '''
  order = tf.cast(tf.experimental.numpy.log2(tf.cast(mat.shape[0],tf.float32)),tf.int16)
  eu = Euler(order)
  fk_grad = generate_diff_sum_grad_fk(mat)
  def obj_fk(x,grad):
    tf_x = tf.constant(x,dtype=tf.float64)
    if grad.size > 0:
      obj = fk_grad(tf_x)
      for i in range(grad.size):
        grad[i] = obj[0].numpy()[i]

    return obj[1].numpy()

  return obj_fk

def generate_obj_sk(mat):
  '''
  generates an objective function for the optimization problem to find the canonical coordinates of the first kind based on the diff_sum.
  '''
  order = tf.cast(tf.experimental.numpy.log2(tf.cast(mat.shape[0],tf.float32)),tf.int16)
  eu = Euler(order)
  sk_grad = generate_diff_sum_grad_sk(mat)
  def obj_sk(x,grad):
    tf_x = tf.constant(x,dtype=tf.float64)
    if grad.size > 0:
      obj = sk_grad(tf_x)
      for i in range(grad.size):
        grad[i] = obj[0].numpy()[i]

    return obj[1].numpy()

  return obj_sk

In [8]:
# unitary matrices to be coordinated
h_gate = tf.cast(tf.constant([[1.,1.],[1.,-1.]])/tf.sqrt(2.),dtype=tf.complex128); # Hadarmard gate
s_gate = tf.constant([[1,0],[0,-1.0j]],dtype=tf.complex128); # S gate
t_gate = tf.constant(np.array([[1,0],[0,np.exp(1.0j*np.pi/8)]],dtype=np.complex128)); # T gate
cnot_gate = tf.constant(np.array([[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]],dtype=np.complex128)); #CNOT gate

In [9]:
unitary_target = h_gate
dim = tf.reduce_prod(unitary_target.shape).numpy().astype(int).item()

##### 알고리즘 실행(최적화)
##### 아래의 코드들은 결국 initial value(np.ones(dim))의 matrix를 만들고 싶어하는 unitary matrix(h_gate, s_gate)과의 차이를 줄이는 방향으로 최적화 하여 그 matrix를 구하고 싶어합니다.(또한 그에 따른 eigenvector와 eigenvalue 역시 구하고 싶어 합니다.) nlopt의 opt 객체를 생성하여 그 opt 객체 내의 set_min_objective 메서드를 이용해 이를 최적화합니다.

In [10]:
logging.getLogger('tensorflow').setLevel(logging.ERROR) # quiets Tensorflow warnings.
obj_fk = generate_obj_fk(unitary_target) # generates an objective function for a target unitary matrix.
opt = nlopt.opt(nlopt.LD_LBFGS,dim) # chooses an optimization algorithm. # LBFGS 알고리즘을 이용해 최적화를 실행합니다.
opt.set_min_objective(obj_fk) # sets the objective function for the chosen optimization algorithm.  #opt 인스턴스의 최적화 함수를 설정합니다.
opt.set_xtol_rel(1e-5) # sets the tolerance for the convergence.    #최적화 tolerance를 설정합니다.
theta_opt_fk = opt.optimize(np.ones(dim)) # sets the initial varaibles.     #초기 값을 설정합니다.
obj_final = opt.last_optimum_value() # assigns the variables of the last iteration.
# prints results of the optimization algorithm
print("minimum at",theta_opt_fk)
print("the objective function converges to", obj_final)
print("optimization result: ",opt.last_optimize_result())

minimum at [ 3.14159265e+00  2.22144147e+00 -7.51315101e-11  2.22144147e+00]
the objective function converges to 5.858023705462033e-16
optimization result:  1


In [11]:
logging.getLogger('tensorflow').setLevel(logging.ERROR) # quiets Tensorflow warnings.
obj_sk = generate_obj_sk(h_gate) # generates an objective function for a target unitary matrix.
opt = nlopt.opt(nlopt.LD_LBFGS,16) # chooses an optimization algorithm.
opt.set_min_objective(obj_sk) # sets the objective function for the chosen optimization algorithm.
opt.set_xtol_rel(1e-5) # sets the tolerance for the convergence.
theta_opt_sk = opt.optimize(np.ones(16)) # sets the initial varaibles.
obj_final = opt.last_optimum_value() # assigns the variables of the last iteration.
# prints results of the optimization algorithm
print("minimum at",theta_opt_sk)
print("the objective function converges to", obj_final)
print("optimization result: ",opt.last_optimize_result())

minimum at [3.14159265 1.57079632 1.5707963  1.57079632 1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.        ]
the objective function converges to 9.110270824146652e-16
optimization result:  4


In [12]:
# validation
eu1 = Euler(1)
eu2 = Euler(2)
fk_mat_su2 = generate_first_kind(eu1)
fk_mat_su4 = generate_first_kind(eu2)
sk_mat_su2 = generate_second_kind(eu1)
sk_mat_su4 = generate_second_kind(eu2)

In [13]:
fk_mat_su2(theta_opt_fk)

<tf.Tensor: shape=(2, 2), dtype=complex128, numpy=
array([[ 0.70710678+2.39601672e-11j,  0.70710678+9.63573665e-12j],
       [ 0.70710678+5.74658654e-11j, -0.70710678-4.31413794e-11j]])>

In [14]:
unitary_target = cnot_gate
dim = tf.reduce_prod(unitary_target.shape).numpy().astype(int).item()

In [15]:
dim

16

In [16]:
logging.getLogger('tensorflow').setLevel(logging.ERROR) # quiets Tensorflow warnings.
obj_fk = generate_obj_fk(unitary_target) # generates an objective function for a target unitary matrix.
opt = nlopt.opt(nlopt.LD_LBFGS,dim) # chooses an optimization algorithm.
opt.set_min_objective(obj_fk) # sets the objective function for the chosen optimization algorithm.
opt.set_xtol_rel(1e-5) # sets the tolerance for the convergence.
theta_opt_fk = opt.optimize(np.ones(dim)) # sets the initial varaibles.
obj_final = opt.last_optimum_value() # assigns the variables of the last iteration.
# prints results of the optimization algorithm
print("minimum at",theta_opt_fk)
print("the objective function converges to", obj_final)
print("optimization result: ",opt.last_optimize_result())

minimum at [ 1.57079634e+00  1.57079631e+00  7.08445492e-09  7.08445507e-09
  7.08445500e-09 -1.69169595e-08 -2.08570818e-09 -2.32231501e-08
  7.08445500e-09 -1.69169595e-08 -2.32231501e-08 -2.08570818e-09
  1.57079631e+00  1.57079629e+00 -1.69169596e-08 -1.69169598e-08]
the objective function converges to 3.436238964984065e-15
optimization result:  4


In [17]:
logging.getLogger('tensorflow').setLevel(logging.ERROR) # quiets Tensorflow warnings.
obj_sk = generate_obj_sk(h_gate) # generates an objective function for a target unitary matrix.
opt = nlopt.opt(nlopt.LD_LBFGS,16) # chooses an optimization algorithm.
opt.set_min_objective(obj_sk) # sets the objective function for the chosen optimization algorithm.
opt.set_xtol_rel(1e-5) # sets the tolerance for the convergence.
theta_opt_sk = opt.optimize(np.ones(16)) # sets the initial varaibles.
obj_final = opt.last_optimum_value() # assigns the variables of the last iteration.
# prints results of the optimization algorithm
print("minimum at",theta_opt_sk)
print("the objective function converges to", obj_final)
print("optimization result: ",opt.last_optimize_result())

minimum at [3.14159265 1.57079632 1.5707963  1.57079632 1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.        ]
the objective function converges to 9.110270824146652e-16
optimization result:  4


In [18]:
# validation
eu1 = Euler(2)
eu2 = Euler(4)
fk_mat_su2 = generate_first_kind(eu1)
fk_mat_su4 = generate_first_kind(eu2)
sk_mat_su2 = generate_second_kind(eu1)
sk_mat_su4 = generate_second_kind(eu2)

In [19]:
np.round(fk_mat_su2(theta_opt_fk),6)

array([[ 1.-0.j, -0.+0.j, -0.+0.j, -0.+0.j],
       [ 0.+0.j,  1.-0.j,  0.+0.j, -0.+0.j],
       [ 0.+0.j,  0.+0.j, -0.-0.j,  1.-0.j],
       [ 0.+0.j, -0.+0.j,  1.+0.j,  0.-0.j]])